### PR TITLE
Added support for Cancel event and update for Elm 19.1

### LINKED ISSUE #7: Add support for Cancel Event
I need the ability to determine if the user canceled the modal or if the modal was confirmed/acknowledged.

### LINKED ISSUE #8: Update elm.json to support Elm 19.1
Right now when I try to build the project with the latest Elm version (19.1) it fails because of an outdated dependency from `rtfeldman/elm-css`

### PR DESCRIPTION
**Pull request by anotherhale**
closes #7 
closes #8

### CODE REVIEW

**Comment by anotherhale** [comment]
I don't know why the Modal.elm file ended up with a complete diff of the entire file.  I will look at it again and try to resolve it. The diff should only be about ~20 lines or so.

**Comment by anotherhale** [comment]
Actually when I changed my settings to ignore white space it only showed the ~60 line diff. Not sure if it is an issue or not.

**Comment by s-m-i-t-a** [comment]
> Actually when I changed my settings to ignore white space it only showed the ~60 line diff. Not sure if it is an issue or not.

Hi, are you working on Windows OS? Probably yes, then turn on the unix file format compatibility in the editor.

**Comment by anotherhale** [comment]
Hopefully that resolved it. I am working on updating the example file to demonstrate this update. It might take me a few days though.

**Review by s-m-i-t-a — APPROVED** [review]

**Comment by ondrej-tucek** [comment]
LGTM, the format compatibility is now correct. Perhaps for the updating of example file would be better make new PR...

Also your hands are free if you want to use other css framework than Foundation...

**Review by ondrej-tucek — APPROVED** [review]

**Pull request merged**
